server:
  port: 8080
  servlet:
    context-path: /learnweb

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/learnweb"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "ptkirmBwRDF2MPx+TWhCrwHHGYPJh6lYKYaevxH+dhtu6Vmgnlj/7EPbMiN2SErY"
